/**
 * components/landing/FAQSection.tsx
 *
 * Frequently-asked-questions section for the landing page,
 * built with the shadcn Accordion (Base UI).
 */

import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";

const FAQ_ITEMS = [
  {
    question: "What is HealthSetu and how does it work?",
    answer:
      "HealthSetu is a patient-centric health records platform inspired by India's Ayushman Bharat Digital Mission (ABDM). It gives you a unified timeline of every hospital visit, prescription, lab report, and discharge summary — all in one place. When you visit a new doctor, you grant consent for them to view your prior records so they can make informed decisions without you repeating your medical history.",
  },
  {
    question: "Is my health data safe and private?",
    answer:
      "Absolutely. You own your data and control who can access it. Every sharing action requires your explicit consent — you choose which records to share, with which provider, and for how long. You can revoke access at any time. The platform uses encryption at rest and in transit, and no data is shared without your approval.",
  },
  {
    question: "Can I use HealthSetu across multiple hospitals?",
    answer:
      "Yes — that's the core value. Whether you visit Hospital A today and Hospital B next week, your records follow you. When a new provider requests access, you approve it through a simple consent flow, and they instantly see your authorized medical history. Nothing is lost between visits.",
  },
  {
    question: "What kind of records can I store?",
    answer:
      "HealthSetu supports prescriptions, diagnostic lab reports, radiology scans, discharge summaries, vaccination records, and clinical notes. You can also upload scanned documents or PDFs — structured data is extracted via OCR and you verify it before it enters your record.",
  },
  {
    question: "How does the AI assistant work?",
    answer:
      "The AI assistant provides plain-language summaries of your medical reports so you can understand what they mean. It's powered by an LLM and is always grounded in your own records — it won't make things up. Every AI-generated explanation is clearly labelled so you always know what came from a doctor versus what was generated by AI.",
  },
  {
    question: "Is this a real product I can use today?",
    answer:
      "HealthSetu is currently a hackathon prototype built to demonstrate how patient-owned health records could work at scale. All data shown in the demo is synthetic — no real patient information is used. The ABDM-inspired consent and record flows are simulated for demonstration purposes.",
  },
] as const;

export default function FAQSection() {
  return (
    <section
      id="faq"
      aria-labelledby="faq-heading"
      className="py-24 px-4 sm:px-6 lg:px-8 bg-muted/50"
    >
      <div className="max-w-3xl mx-auto">
        {/* Section header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-secondary-tint border border-border/40 text-accent text-xs font-heading font-semibold tracking-wide uppercase mb-4">
            FAQ
          </div>
          <h2
            id="faq-heading"
            className="text-3xl sm:text-4xl lg:text-5xl font-bold font-heading text-foreground mb-4"
          >
            Frequently asked questions
          </h2>
          <p className="text-base sm:text-lg text-muted-foreground max-w-xl mx-auto">
            Everything you need to know about HealthSetu and how it keeps your
            health data safe.
          </p>
        </div>

        {/* Accordion */}
        <div className="bg-white/80 backdrop-blur-sm rounded-2xl border border-border/40 p-2 sm:p-4">
          <Accordion className="w-full">
            {FAQ_ITEMS.map(({ question, answer }, idx) => (
              <AccordionItem
                key={idx}
                className="border-b border-border/30 last:border-b-0"
              >
                <AccordionTrigger className="py-5 px-3 text-base font-semibold font-heading text-foreground hover:no-underline hover:text-accent [&>svg]:text-accent">
                  {question}
                </AccordionTrigger>
                <AccordionContent>
                  <p className="text-muted-foreground leading-relaxed px-3 pb-4">
                    {answer}
                  </p>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
